#ifndef INCLUDE_RENDERER_BUFFER
#define INCLUDE_RENDERER_BUFFER

// NOTE: Some of these only apply on vulkan.
// I can probably just remap them in the background on other apis.
enum RENDERER_BUFFER_TYPE
{
	RENDERER_BUFFER_TYPE_UNIFORM,
	RENDERER_BUFFER_TYPE_UNIFORM_DYNAMIC,
	RENDERER_BUFFER_TYPE_STORAGE,
	RENDERER_BUFFER_TYPE_STORAGE_DYNAMIC,
	RENDERER_BUFFER_TYPE_STAGING,
};

#endif